apiVersion: v1
kind: Pod
metadata:
  name: huginn
  labels: 
    name: huginn
spec: 
  containers: 
    - image: gcr.io/nice-argon-102023/huginn
      name: huginn
      imagePullPolicy: Always
      env:
        - name: HUGINN_DATABASE_NAME
          # change this - must match mysql.yaml value
          value: huginn
        - name: HUGINN_DATABASE_USERNAME
          # change this - must match mysql.yaml value
          value: huginn
        - name: HUGINN_DATABASE_PASSWORD
          # change this - must match mysql.yaml password
          value: somethingsecret
        - name: HUGINN_DATABASE_ADAPTER
          value: 'mysql2'
        - name: HUGINN_DATABASE_ENCODING
          value: 'utf8'
        - name: HUGINN_DATABASE_RECONNECT
          value: 'true'
        - name: HUGINN_DATABASE_POOL
          value: '10'
        - name: HUGINN_DATABASE_HOST
          value: '173.194.255.22'
        - name: HUGINN_DATABASE_PORT
          value: '3306'
        - name: HUGINN_INVITATION_CODE
          value: secret
        - name: HUGINN_RAILS_ENV
          value: production
        - name: HUGINN_FORCE_SSL
          value: 'false'
        - name: HUGINN_DOMAIN
          value: 'nuistics.com:3000'
        - name: HUGINN_SMTP_DOMAIN
          value: gmail.com
        - name: HUGINN_SMTP_USER_NAME
          value: shaunaa126@gmail.com
        - name: HUGINN_SMTP_PASSWORD
          value: ''
        - name: HUGINN_SMTP_SERVER
          value: smtp.gmail.com
        - name: HUGINN_SMTP_PORT
          value: '587'
        - name: HUGINN_SMTP_AUTHENTICATION
          value: plain
        - name: HUGINN_SMTP_ENABLE_STARTTLS_AUTO
          value: 'true'
        - name: HUGINN_SEND_EMAIL_IN_DEVELOPMENT
          value: 'false'
        - name: HUGINN_EMAIL_FROM_ADDRESS
          value: shaunaa126@gmail.com
      ports: 
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
          name: huginn
#      volumeMounts:
#          name must match the volume name below
#        - name: huginn-persistent-storage
#          mount path within the container
#         mountPath: /var/lib/huginn
#  volumes:
#    - name: huginn-persistent-storage
#      gcePersistentDisk:
#         This GCE PD must already exist.
#        pdName: huginn-disk
#        fsType: ext4
