apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: huginnfrontend
  name: huginnfrontend
spec: 
  ports:
    # the port that this service should serve on
    - port: 3000
      targetPort: 3000
      protocol: TCP
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: huginn
  type: LoadBalancer
